{% set name = "UQpy" %}
{% set version = "4.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: aeed10a25e37c93e49b659876a13834e2fe3f19c36bcecc5445c8444fb569645

build:
  number: 0
  noarch: python
  script: python setup.py {{ version }} install --single-version-externally-managed --root=/

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools
  run:
    - fire
    - matplotlib-base
    - numpy
    - python >=3.9
    - scikit-learn
    - scipy
    - setuptools
    - beartype ==0.9.1

test:
  commands:
    - test -d /home/conda/feedstock_root/build_artifacts

about:
  home: https://github.com/SURGroup/UQpy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: |
    UQpy (Uncertainty Quantification with python) is a general purpose 
    Python toolbox for modeling uncertainty in physical and mathematical systems.
  doc_url: https://sites.google.com/site/jhusurg/UQpy?authuser=0
  dev_url: https://github.com/SURGroup/UQpy

extra:
  recipe-maintainers:
    - volpatto
    - dimtsap
