{% set name = "UQpy" %}
{% set version = "4.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3c790b273adaf5e80dd25880a7438d8ad19a84aa7c02670e9779a7818c5f1493

build:
  number: 0
  noarch: python
  script: python setup.py {{ version }} install --single-version-externally-managed --root=/

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
  run:
    - fire
    - matplotlib-base
    - numpy
    - python >=3.8
    - scikit-learn
    - scipy
    - setuptools

test:
  commands:
    - test -d /home/conda/feedstock_root/build_artifacts

about:
  home: https://github.com/SURGroup/UQpy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: |
    UQpy (Uncertainty Quantification with python) is a general purpose 
    Python toolbox for modeling uncertainty in physical and mathematical systems.
  doc_url: https://sites.google.com/site/jhusurg/UQpy?authuser=0
  dev_url: https://github.com/SURGroup/UQpy

extra:
  recipe-maintainers:
    - volpatto
    - dimtsap
