travis:
  secure:
    BINSTAR_TOKEN: igDp1wksJMvudK2arpgO/9CLGb8gJ1IawD+zoVjIC1dZy0kZwSgr+WHVvjib3uDfCxWmWz2d6+CQuSXu/iD4XVbNn/dG0gn9gOOy6e97Cm2t4ewPsJwjoN0h5Xt+TRK8k8wZOgqm755Z6FYPTXaBc8Ju14IeuLmGj2MlBm62XhKvNLkXFAXmhbPkMucwlziMUPMmI5E6mM647suEB8l/J5bT/n7tkC5Fu5iylSvO/qztP6bgGGpViyLqIkzVnu0k/uSLvLrdU0w3ENdWLlF7fb9syKwuzs12obJMyK4KPd0drKUbLVi+xgJ5MlFEE4GEmYSQzkomZj5xaoVt6qTEGdcIMJbINcsAGffwgJeDrFhLV5ZoGi/D+pjSimKM0ppNIXA9Pelk3aYJtp6cikvl+c6sMHh7qs8KfTUK48n3OIEgOzvbHhzy+t7vj+7t9VfrvbOGYj1D9W5k4z26QxmTZwhXaQQH2WeKQQj4EjjhluCTY2bMitybrBjA4KxckGPhD2V6vPh8Ld/Sr8OHaAHdrNTJuazCefm1/7QuoiymkkNP5j3IeLKzrDubLif7rIbdmh/9Ow+OS/5S3roY4e5Y5MTLxxrS2U3YheeuHOyIjPpxA3BMc1M/0kxEnm8L5Hc7KtPSiVCTaqguXH+TMTntRi27Jq7YjYu8W5i/wrVBe7M=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
